[config]
schemaVersion = "0.0.1"

[package]
namespace = "Abevol"
name = "MultiReward"
versionNumber = "1.0.4"
description = "Get multiple room rewards."
websiteUrl = "https://github.com/abevol/MultiReward"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.28"
SGG_Modding-ENVY = "1.0.1"
SGG_Modding-Chalk = "2.1.0"
SGG_Modding-ReLoad = "1.0.1"
SGG_Modding-SJSON = "1.0.0"
SGG_Modding-ModUtil = "3.1.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./"

[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]
